better "no results found" messages for HTML & text
Remove "no results found" message emission from dasht-query-html(1).
Instead, move that responsibility to the HTML & text user interfaces.

diff --git a/bin/dasht b/bin/dasht
--- a/bin/dasht
+++ b/bin/dasht
@@ -60,13 +60,15 @@
 # Distributed under the terms of the ISC license (see the LICENSE file).
 
 trap 'exit 1' TERM # exit silently when killed by pipefail emulation below
-{
-  dasht-query-html "$@" ||
+if ! dasht-query-html "$@"; then
+  # notify user when no results are found so they can refine their search
+  pat=$1; shift; echo "dasht: '$pat' not found in ${*:-any} docsets" >&2
+
   # emulate pipefail (which POSIX lacks) by killing off the w3m(1) process
   # below (which starts up simultaneously alongside this pipeline segment)
   # and then proceed to kill this script to generate a nonzero exit status
   kill $(ps -e -o comm,ppid,pid | sed -n "s/^w3m *$$ //p") $$
-} |
+fi |
 w3m -T text/html \
     -o confirm_qq=false \
     -o color=true \
