add support for using existing Dash.app docsets

diff --git a/bin/dasht-docsets-update b/bin/dasht-docsets-update
--- a/bin/dasht-docsets-update
+++ b/bin/dasht-docsets-update
@@ -33,6 +33,16 @@
 #   If undefined, its value is assumed to be `$XDG_DATA_HOME/dasht/docsets/`
 #   or, if `XDG_DATA_HOME` is undefined, `$HOME/.local/share/dasht/docsets/`.
 #
+# `DASHT_USE_DASH_APP`
+#   Set to "true" to use Dash.app's (MacOS only) docset library. Disables
+#   docset management commands (install, remove, update). Also changes the
+#   default `DASHT_DOCSETS_DIR` to "~/Library/Application Support/Dash".
+#
+# ## EXIT STATUS
+#
+# 46
+#   Command was not executed because `DASHT_USE_DASH_APP` is set.
+#
 # ## SEE ALSO
 #
 # dasht-docsets-extract(1), dasht-docsets-install(1), dasht-docsets-remove(1),
@@ -46,6 +56,13 @@
 # Distributed under the terms of the ISC license (refer to README file).
 
 : ${DASHT_DOCSETS_DIR:=${XDG_DATA_HOME:-$HOME/.local/share}/dasht/docsets}
+: ${DASHT_USE_DASH_APP:=false}
+
+if $DASHT_USE_DASH_APP; then
+  echo "extract, install, remove, and update operations are disabled when \
+    DASHT_USE_DASH_APP=true." >&2
+  exit 46
+fi
 
 dasht-docsets "$@" | while read -r docset; do
   ls "$DASHT_DOCSETS_DIR/$docset"*.tgz
